language: node_js
node_js:
- '6'

script:
  - yarn test

before_deploy:
  - yarn global add auto-dist-tag
  - auto-dist-tag --write

deploy:
  provider: npm
  email: tobias.bieniek@gmx.de
  api_key:
    secure: jYs+96GDEqxFhI+DFvyAxxd6P21AH8IueK0iUZoiwF6G2yxuHjq95vkcu0AmG1QUgTMu7TSWNAlRd3StXhVN6OWgyMTdgJuWesrLTpnvUACRDQ1nJzy+6gwfmP4TORq8qjXWYTT1Dob/BxKIFbqpwt9zMjmPaqcwOYZTQm0g5CQ0A8YsPtr3ydb8oEEPrBNnhbsnUHPFRY9loADcP6FDoDYqlKH95q2DIwzJz/ar2gmw9X7DxXrC4XxtxPgf+ccwyWTwHUc3xeUd5U3vyWxrzoSdZX9PE8L+B6YAXDG+KSEiiITfWgFVNGJnm2QMdAKgJYCQtQBOHlZOeLNXdBLKbRg0Gfe5PAc2MuL26WfA3YveH8Ed2vn9UPEtM3W9MHLcQcoZk0Bp+BtqDggeOT/ItjvThAbiicJHEC1Kenq6/XryhBO/0UN0bzPnocR3FYw+SlQ+WYiaDeHggP2qrTkJbStFMhOLlhQmDQqdubeLlWpPz5SlBN3TNZIWrJgWB0weFvABOw6Uc4CUsbfQ79YUd6uchmkqsegJZ0/672+HdLLuzQ4jYASCTK1od5RfoTh/h4MowtMOjymZrT7wns8Ns2nkBw7KswYXhCpBB/JxyC6Qi2Z2U2p5xuenI8QAH3d/GjeYwg2QP3NDygHGeKGP/VwHEnHzJ7/ErGVpmf/k8Gg=
  on:
    tags: true
    repo: Turbo87/igc-filename-parser
